### ISSUE TITLE
inverted_pendulum/run.py fails to reach the performance as in the paper

### ISSUE THREAD

**Issue by 4kubo** [sebascuri/hucrl#1]
I am interested in your work over the H-UCRL algorithm introduced in Curi, S., Berkenkamp, F., & Krause, A. (2020). Efficient Model-Based Reinforcement Learning through Optimistic Policy Search and Planning.
I believe the work is very important.

Currently I have one question and one bug report.

My question is how can I run the H-UCRL algorithm for reproduction of the experiments described in the paper, e.g. at Appendix B.2?
I understand that the execution "% python exps/inverted_pendulum/run.py" with default value agent_name="mbmpo" corresponds to the experiment of App. B.2.1 though the some parameter configurations may differ. But how about the other experiments? The task is fixed only to InvertedPendulum as in the function
https://github.com/sebascuri/hucrl/blob/ec3a1967ca75991b198c41c4f2b8d1678e77307a/exps/inverted_pendulum/util.py#L428
Do we need to implement by ourselves for the other tasks? Or is it possible if we use exps/mujoco/run.py with some modification? Because it seems that MBMPO alg. described in the papers appendix B.1 is not supported;
https://github.com/sebascuri/hucrl/blob/ec3a1967ca75991b198c41c4f2b8d1678e77307a/exps/mujoco/run.py#L30-L38
where an Agent class is called from rllib module.
I hope I can execute H-UCRL alg. with MBMPO using exps/mujoco/run.py because this way make it easy to compare the other configurations.

The bug I found is about the execution of exps/inverted_pendulum/run.py. First of all I found that just execution "% python exps/inverted_pendulum/run.py" fails to swing up the pendulum even after 20 episodes. With two modification it succeeded.
1. Set PLAN_HORIZON to non-zero value e.g. 50 in https://github.com/sebascuri/hucrl/blob/ec3a1967ca75991b198c41c4f2b8d1678e77307a/exps/inverted_pendulum/run.py#L17
2. Change shape of variable `returns` from [..., -1, :] to [..., -1] in the source code of rllib
https://github.com/sebascuri/rllib/blob/8abca6110fdbc9adeaaff1f92a08e7d97f7fe408/rllib/util/value_estimation.py#L206
This is based on an observation of a shape mismatch when calculating td_error in
https://github.com/sebascuri/hucrl/blob/ec3a1967ca75991b198c41c4f2b8d1678e77307a/hucrl/algorithms/mbmpo.py#L104
The second bug is critical but this workaround is unacceptable.

A minor question is even with the modification above and no action penalty, the `Train Return` does not reach to 300 as reported in the paper e.g. by Fig.1. but about 220 at best. Is this enough?

**Comment by sebascuri** [comment]
Hi, This is extremely strange. I run the code without any problem and with default values to obtain the results in the paper. Maybe there is some issue in the updates of rllib. I will definitely look into this and get back to you. 

For the mujoco experiments you can try out BPTT or MPC as the agent :). I think it is also possible to make MBMPO work but I don't know the exact hyper parameters here.

**Comment by sebascuri** [comment]
Hi, effectively there was an issue with the versions of RL-lib that I didn't update in my local installation. I am working on these to fix them ASAP.

**Comment by sebascuri** [comment]
Hi, could you check if it works out now? For the mujoco you should also find the config of algorithms that work, ie data augmentation, BPTT, MVE and MPC :)

**Comment by 4kubo** [comment]
I'm so sorry for my late reply. I have struggled to setup my new computer.

Thank you for your support. I observed that I can run the code of 91da46a without any error.
In my new environment, however, values obtained from `python exps/inverted_pendulum/run.py` are different from the paper (Fig. 13?). I observed it reaches over 200 Sim Return after 13 episodes. I think this difference is because of my python environment. For example, the version of numpy in my conda environment is 1.20.1, while torch==1.6.0.
Anyway, I think the bug I mentioned has been fixed. Thank you ; )

**Comment by 4kubo** [comment]
> For the mujoco experiments you can try out BPTT or MPC as the agent :). I think it is also possible to make MBMPO work but I don't know the exact hyper parameters here.

In appedix B.1 in the paper, it is described that a modification of MPO is used as PolicySearch algorithm. Is not this relavant to MBMPO? From this description I expected that mujoco/run.py corresponds to experiments from B.2.2 to B.2.6 including HalfCheetah (mujoco).
I may have misunderstood your paper.
